language: php

git:
  depth: 1

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.1
    - php: 7.0
      env: LINT=true
    - php: 5.6

  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

notifications:
  email: false

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload --optimize

script:
  # Verify coding standard compliance only once
  - if [[ $LINT = true ]]; then
      composer ship-it-emoji:cs-lint;
    fi
  - composer ship-it-emoji:test
